"""Database Seeding Script for PSG College of Arts & Science
MCA Semester III Timetable & Academic Calendar 2026-2027.
"""
from sqlalchemy.orm import Session
from ..database import SessionLocal, engine, Base
from ..models import Subject, Timetable, CalendarEvent


def seed_data(db: Session):
    # Ensure tables are created
    Base.metadata.create_all(bind=engine)

    # 1. Clear existing data to allow idempotent seeding
    db.query(Timetable).delete()
    db.query(Subject).delete()
    db.query(CalendarEvent).delete()
    db.commit()

    # 2. Seed Subjects
    subjects_data = [
        {
            "code": "25CAP314",
            "name": "Artificial Intelligence",
            "description": "Covers search algorithms, knowledge representation, game playing, heuristic search, and intelligent agent architectures.",
            "class_type": "Theory",
            "faculty": "Department of MCA Faculty",
        },
        {
            "code": "25CAP321",
            "name": "Artificial Intelligence Lab",
            "description": "Practical implementation of AI search algorithms, heuristic agents, and Python game development in Room E-208.",
            "class_type": "Lab",
            "faculty": "Department of MCA Faculty",
        },
        {
            "code": "25CAP315",
            "name": "Machine Learning",
            "description": "Supervised, unsupervised algorithms, model evaluation, and regression/classification workflows.",
            "class_type": "Theory",
            "faculty": "Department of MCA Faculty",
        },
        {
            "code": "25CAP322",
            "name": "Machine Learning Lab",
            "description": "Hands-on machine learning experiments, data preprocessing, and model pipelines in Room E-311.",
            "class_type": "Lab",
            "faculty": "Department of MCA Faculty",
        },
        {
            "code": "25CAP316",
            "name": "Full Stack Development",
            "description": "Client-side and server-side web engineering, modern JavaScript, Node.js, Express, and database integration.",
            "class_type": "Theory",
            "faculty": "Department of MCA Faculty",
        },
        {
            "code": "25CAP323",
            "name": "Full Stack Development Lab",
            "description": "Full stack hands-on lab sessions, responsive UI engineering, and web applications in Room E-208.",
            "class_type": "Lab",
            "faculty": "Department of MCA Faculty",
        },
        {
            "code": "25CAP320A_B",
            "name": "Agile Methodologies / Software Quality Assurance (AM/SQA)",
            "description": "Elective course covering software testing, verification, validation, CMMI, metrics, Agile mindset, Scrum, and XP practices.",
            "class_type": "Major Elective",
            "faculty": "Dr. L. Thara, Dr. M. Mohanapriya & Dr. R.K",
        },
        {
            "code": "25IDCCAPT",
            "name": "Trans-Disciplinary Course (TDC - PG)",
            "description": "Interdisciplinary theory course for postgraduate cluster on data analytics, statistical reasoning, and technical discussions.",
            "class_type": "Theory",
            "faculty": "Postgraduate Faculty",
        },
        {
            "code": "25IDCCAPP",
            "name": "Trans-Disciplinary Course Lab (TDC Lab - PG)",
            "description": "Interdisciplinary data analytics practicals and technical discussion lab in Room E-311.",
            "class_type": "Lab",
            "faculty": "Postgraduate Faculty",
        },
    ]

    subject_map = {}
    for s_item in subjects_data:
        subj = Subject(**s_item)
        db.add(subj)
        db.flush()
        subject_map[s_item["name"]] = subj.id

    # 3. Seed Timetable (MCA Semester III)
    # Day I to Day VI
    timetable_data = [
        # --- DAY I ---
        {
            "day_order": "Day I",
            "start_time": "10:00 AM",
            "end_time": "11:00 AM",
            "subject": "TDC (PG)",
            "room": "MCA Classroom",
            "faculty": "Postgraduate Faculty",
            "class_type": "Theory",
            "subject_id": subject_map.get("Trans-Disciplinary Course (TDC - PG)"),
        },
        {
            "day_order": "Day I",
            "start_time": "11:00 AM",
            "end_time": "12:00 PM",
            "subject": "AI",
            "room": "MCA Classroom",
            "faculty": "Department of MCA Faculty",
            "class_type": "Theory",
            "subject_id": subject_map.get("Artificial Intelligence"),
        },
        {
            "day_order": "Day I",
            "start_time": "12:00 PM",
            "end_time": "12:15 PM",
            "subject": "Break",
            "room": None,
            "faculty": None,
            "class_type": "Break",
            "subject_id": None,
        },
        {
            "day_order": "Day I",
            "start_time": "12:15 PM",
            "end_time": "1:15 PM",
            "subject": "ML",
            "room": "MCA Classroom",
            "faculty": "Department of MCA Faculty",
            "class_type": "Theory",
            "subject_id": subject_map.get("Machine Learning"),
        },
        {
            "day_order": "Day I",
            "start_time": "1:15 PM",
            "end_time": "2:00 PM",
            "subject": "Lunch Break",
            "room": None,
            "faculty": None,
            "class_type": "Lunch",
            "subject_id": None,
        },
        {
            "day_order": "Day I",
            "start_time": "2:00 PM",
            "end_time": "3:00 PM",
            "subject": "FSD",
            "room": "MCA Classroom",
            "faculty": "Department of MCA Faculty",
            "class_type": "Theory",
            "subject_id": subject_map.get("Full Stack Development"),
        },
        {
            "day_order": "Day I",
            "start_time": "3:00 PM",
            "end_time": "5:00 PM",
            "subject": "AM/SQA",
            "room": "MCA Classroom",
            "faculty": "Dr. L. Thara & Dr. R.K",
            "class_type": "Theory",
            "subject_id": subject_map.get("Agile Methodologies / Software Quality Assurance (AM/SQA)"),
        },

        # --- DAY II ---
        {
            "day_order": "Day II",
            "start_time": "10:00 AM",
            "end_time": "11:00 AM",
            "subject": "TDC (PG)",
            "room": "MCA Classroom",
            "faculty": "Postgraduate Faculty",
            "class_type": "Theory",
            "subject_id": subject_map.get("Trans-Disciplinary Course (TDC - PG)"),
        },
        {
            "day_order": "Day II",
            "start_time": "11:00 AM",
            "end_time": "12:00 PM",
            "subject": "ML Lab",
            "room": "E-311",
            "faculty": "Department of MCA Faculty",
            "class_type": "Lab",
            "subject_id": subject_map.get("Machine Learning Lab"),
        },
        {
            "day_order": "Day II",
            "start_time": "12:00 PM",
            "end_time": "12:15 PM",
            "subject": "Break",
            "room": None,
            "faculty": None,
            "class_type": "Break",
            "subject_id": None,
        },
        {
            "day_order": "Day II",
            "start_time": "12:15 PM",
            "end_time": "1:15 PM",
            "subject": "ML Lab",
            "room": "E-311",
            "faculty": "Department of MCA Faculty",
            "class_type": "Lab",
            "subject_id": subject_map.get("Machine Learning Lab"),
        },
        {
            "day_order": "Day II",
            "start_time": "1:15 PM",
            "end_time": "2:00 PM",
            "subject": "Lunch Break",
            "room": None,
            "faculty": None,
            "class_type": "Lunch",
            "subject_id": None,
        },
        {
            "day_order": "Day II",
            "start_time": "2:00 PM",
            "end_time": "3:00 PM",
            "subject": "FSD",
            "room": "MCA Classroom",
            "faculty": "Department of MCA Faculty",
            "class_type": "Theory",
            "subject_id": subject_map.get("Full Stack Development"),
        },
        {
            "day_order": "Day II",
            "start_time": "3:00 PM",
            "end_time": "5:00 PM",
            "subject": "ML",
            "room": "MCA Classroom",
            "faculty": "Department of MCA Faculty",
            "class_type": "Theory",
            "subject_id": subject_map.get("Machine Learning"),
        },

        # --- DAY III ---
        {
            "day_order": "Day III",
            "start_time": "10:00 AM",
            "end_time": "11:00 AM",
            "subject": "TDC (PG)",
            "room": "MCA Classroom",
            "faculty": "Postgraduate Faculty",
            "class_type": "Theory",
            "subject_id": subject_map.get("Trans-Disciplinary Course (TDC - PG)"),
        },
        {
            "day_order": "Day III",
            "start_time": "11:00 AM",
            "end_time": "12:00 PM",
            "subject": "FSD Lab",
            "room": "E-208",
            "faculty": "Department of MCA Faculty",
            "class_type": "Lab",
            "subject_id": subject_map.get("Full Stack Development Lab"),
        },
        {
            "day_order": "Day III",
            "start_time": "12:00 PM",
            "end_time": "12:15 PM",
            "subject": "Break",
            "room": None,
            "faculty": None,
            "class_type": "Break",
            "subject_id": None,
        },
        {
            "day_order": "Day III",
            "start_time": "12:15 PM",
            "end_time": "1:15 PM",
            "subject": "AM/SQA",
            "room": "MCA Classroom",
            "faculty": "Dr. M. Mohanapriya & Dr. R.K",
            "class_type": "Theory",
            "subject_id": subject_map.get("Agile Methodologies / Software Quality Assurance (AM/SQA)"),
        },
        {
            "day_order": "Day III",
            "start_time": "1:15 PM",
            "end_time": "2:00 PM",
            "subject": "Lunch Break",
            "room": None,
            "faculty": None,
            "class_type": "Lunch",
            "subject_id": None,
        },
        {
            "day_order": "Day III",
            "start_time": "2:00 PM",
            "end_time": "3:00 PM",
            "subject": "AM/SQA",
            "room": "MCA Classroom",
            "faculty": "Dr. M. Mohanapriya & Dr. R.K",
            "class_type": "Theory",
            "subject_id": subject_map.get("Agile Methodologies / Software Quality Assurance (AM/SQA)"),
        },
        {
            "day_order": "Day III",
            "start_time": "3:00 PM",
            "end_time": "5:00 PM",
            "subject": "AI",
            "room": "MCA Classroom",
            "faculty": "Department of MCA Faculty",
            "class_type": "Theory",
            "subject_id": subject_map.get("Artificial Intelligence"),
        },

        # --- DAY IV ---
        {
            "day_order": "Day IV",
            "start_time": "10:00 AM",
            "end_time": "12:00 PM",
            "subject": "TDC Lab - PG",
            "room": "E-311",
            "faculty": "Postgraduate Faculty",
            "class_type": "Lab",
            "subject_id": subject_map.get("Trans-Disciplinary Course Lab (TDC Lab - PG)"),
        },
        {
            "day_order": "Day IV",
            "start_time": "12:00 PM",
            "end_time": "12:15 PM",
            "subject": "Break",
            "room": None,
            "faculty": None,
            "class_type": "Break",
            "subject_id": None,
        },
        {
            "day_order": "Day IV",
            "start_time": "12:15 PM",
            "end_time": "1:15 PM",
            "subject": "AI",
            "room": "MCA Classroom",
            "faculty": "Department of MCA Faculty",
            "class_type": "Theory",
            "subject_id": subject_map.get("Artificial Intelligence"),
        },
        {
            "day_order": "Day IV",
            "start_time": "1:15 PM",
            "end_time": "2:00 PM",
            "subject": "Lunch Break",
            "room": None,
            "faculty": None,
            "class_type": "Lunch",
            "subject_id": None,
        },
        {
            "day_order": "Day IV",
            "start_time": "2:00 PM",
            "end_time": "5:00 PM",
            "subject": "FSD Lab",
            "room": "E-208",
            "faculty": "Department of MCA Faculty",
            "class_type": "Lab",
            "subject_id": subject_map.get("Full Stack Development Lab"),
        },

        # --- DAY V ---
        {
            "day_order": "Day V",
            "start_time": "10:00 AM",
            "end_time": "11:00 AM",
            "subject": "FSD",
            "room": "MCA Classroom",
            "faculty": "Department of MCA Faculty",
            "class_type": "Theory",
            "subject_id": subject_map.get("Full Stack Development"),
        },
        {
            "day_order": "Day V",
            "start_time": "11:00 AM",
            "end_time": "12:00 PM",
            "subject": "ML",
            "room": "MCA Classroom",
            "faculty": "Department of MCA Faculty",
            "class_type": "Theory",
            "subject_id": subject_map.get("Machine Learning"),
        },
        {
            "day_order": "Day V",
            "start_time": "12:00 PM",
            "end_time": "12:15 PM",
            "subject": "Break",
            "room": None,
            "faculty": None,
            "class_type": "Break",
            "subject_id": None,
        },
        {
            "day_order": "Day V",
            "start_time": "12:15 PM",
            "end_time": "1:15 PM",
            "subject": "AI",
            "room": "MCA Classroom",
            "faculty": "Department of MCA Faculty",
            "class_type": "Theory",
            "subject_id": subject_map.get("Artificial Intelligence"),
        },
        {
            "day_order": "Day V",
            "start_time": "1:15 PM",
            "end_time": "2:00 PM",
            "subject": "Lunch Break",
            "room": None,
            "faculty": None,
            "class_type": "Lunch",
            "subject_id": None,
        },
        {
            "day_order": "Day V",
            "start_time": "2:00 PM",
            "end_time": "3:00 PM",
            "subject": "FSD",
            "room": "MCA Classroom",
            "faculty": "Department of MCA Faculty",
            "class_type": "Theory",
            "subject_id": subject_map.get("Full Stack Development"),
        },
        {
            "day_order": "Day V",
            "start_time": "3:00 PM",
            "end_time": "5:00 PM",
            "subject": "AM/SQA",
            "room": "MCA Classroom",
            "faculty": "Dr. L. Thara & Dr. R.K",
            "class_type": "Theory",
            "subject_id": subject_map.get("Agile Methodologies / Software Quality Assurance (AM/SQA)"),
        },

        # --- DAY VI ---
        {
            "day_order": "Day VI",
            "start_time": "10:00 AM",
            "end_time": "12:00 PM",
            "subject": "AI Lab",
            "room": "E-208",
            "faculty": "Department of MCA Faculty",
            "class_type": "Lab",
            "subject_id": subject_map.get("Artificial Intelligence Lab"),
        },
        {
            "day_order": "Day VI",
            "start_time": "12:00 PM",
            "end_time": "12:15 PM",
            "subject": "Break",
            "room": None,
            "faculty": None,
            "class_type": "Break",
            "subject_id": None,
        },
        {
            "day_order": "Day VI",
            "start_time": "12:15 PM",
            "end_time": "1:15 PM",
            "subject": "AI Lab",
            "room": "E-208",
            "faculty": "Department of MCA Faculty",
            "class_type": "Lab",
            "subject_id": subject_map.get("Artificial Intelligence Lab"),
        },
        {
            "day_order": "Day VI",
            "start_time": "1:15 PM",
            "end_time": "2:00 PM",
            "subject": "Lunch Break",
            "room": None,
            "faculty": None,
            "class_type": "Lunch",
            "subject_id": None,
        },
        {
            "day_order": "Day VI",
            "start_time": "2:00 PM",
            "end_time": "3:00 PM",
            "subject": "ML",
            "room": "MCA Classroom",
            "faculty": "Department of MCA Faculty",
            "class_type": "Theory",
            "subject_id": subject_map.get("Machine Learning"),
        },
        {
            "day_order": "Day VI",
            "start_time": "3:00 PM",
            "end_time": "5:00 PM",
            "subject": "AM/SQA",
            "room": "MCA Classroom",
            "faculty": "Dr. M. Mohanapriya & Dr. R.K",
            "class_type": "Theory",
            "subject_id": subject_map.get("Agile Methodologies / Software Quality Assurance (AM/SQA)"),
        },
    ]

    for t_item in timetable_data:
        db.add(Timetable(**t_item))

    # 4. Seed Academic Calendar Events
    # Covers Odd Semester 2026 and Even Semester 2026/2027 based on official PSG CAS Calendar PDF & Prompt Specifications
    calendar_data = [
        # --- ODD SEMESTER 2026 ---
        {
            "date": "2026-06-15",
            "day": "Monday",
            "event": "Commencement of Classes for Odd Semester",
            "category": "Semester Date",
            "semester": "Odd Semester",
            "is_holiday": False,
            "description": "Classes commence for Odd Semester 2026-2027.",
        },
        {
            "date": "2026-06-21",
            "day": "Sunday",
            "event": "International Yoga Day",
            "category": "Academic Event",
            "semester": "Odd Semester",
            "is_holiday": False,
            "description": "Observance of International Day of Yoga.",
        },
        {
            "date": "2026-06-27",
            "day": "Saturday",
            "event": "Bakrid / Eid al-Adha - Holiday",
            "category": "Holiday",
            "semester": "Odd Semester",
            "is_holiday": True,
            "description": "Public holiday on account of Bakrid.",
        },
        {
            "date": "2026-07-28",
            "day": "Tuesday",
            "event": "Muharram - Holiday",
            "category": "Holiday",
            "semester": "Odd Semester",
            "is_holiday": True,
            "description": "Public holiday on account of Muharram.",
        },
        {
            "date": "2026-08-03",
            "day": "Monday",
            "event": "I CA Test Commences (Odd Semester)",
            "category": "CA Test",
            "semester": "Odd Semester",
            "is_holiday": False,
            "description": "Commencement of First Continuous Assessment (I CA) Tests for Odd Semester.",
        },
        {
            "date": "2026-08-08",
            "day": "Saturday",
            "event": "I CA Test Concludes (Odd Semester)",
            "category": "CA Test",
            "semester": "Odd Semester",
            "is_holiday": False,
            "description": "Conclusion of First Continuous Assessment (I CA) Tests.",
        },
        {
            "date": "2026-08-15",
            "day": "Saturday",
            "event": "Independence Day - Holiday",
            "category": "Holiday",
            "semester": "Odd Semester",
            "is_holiday": True,
            "description": "National Holiday celebrating 80th Independence Day.",
        },
        {
            "date": "2026-08-18",
            "day": "Tuesday",
            "event": "Start Date of Examination Fee Payment (Odd Semester)",
            "category": "Fee Payment",
            "semester": "Odd Semester",
            "is_holiday": False,
            "description": "Start date for payment of Comprehensive Examination fees for Odd Semester.",
        },
        {
            "date": "2026-08-26",
            "day": "Wednesday",
            "event": "Krishna Jayanthi - Holiday",
            "category": "Holiday",
            "semester": "Odd Semester",
            "is_holiday": True,
            "description": "Religious holiday on account of Krishna Jayanthi.",
        },
        {
            "date": "2026-09-01",
            "day": "Tuesday",
            "event": "Last Date for Examination Fee Payment Without Fine (Odd Semester)",
            "category": "Fee Payment",
            "semester": "Odd Semester",
            "is_holiday": False,
            "description": "Last date to pay odd semester examination fee without incurring a late fee fine.",
        },
        {
            "date": "2026-09-05",
            "day": "Saturday",
            "event": "Teachers' Day",
            "category": "Academic Event",
            "semester": "Odd Semester",
            "is_holiday": False,
            "description": "Teachers' Day celebration honoring Dr. Sarvepalli Radhakrishnan.",
        },
        {
            "date": "2026-09-10",
            "day": "Thursday",
            "event": "Last Date for Examination Fee Payment With Fine (Odd Semester)",
            "category": "Fee Payment",
            "semester": "Odd Semester",
            "is_holiday": False,
            "description": "Final deadline to submit examination fee with late penalty.",
        },
        {
            "date": "2026-09-14",
            "day": "Monday",
            "event": "Vinayakar Chathurthi - Holiday",
            "category": "Holiday",
            "semester": "Odd Semester",
            "is_holiday": True,
            "description": "Public holiday for Vinayakar Chathurthi.",
        },
        {
            "date": "2026-09-28",
            "day": "Monday",
            "event": "II CA Test Commences (Odd Semester)",
            "category": "CA Test",
            "semester": "Odd Semester",
            "is_holiday": False,
            "description": "Commencement of Second Continuous Assessment (II CA) Tests for Odd Semester.",
        },
        {
            "date": "2026-10-02",
            "day": "Friday",
            "event": "Gandhi Jayanthi - Holiday",
            "category": "Holiday",
            "semester": "Odd Semester",
            "is_holiday": True,
            "description": "National holiday on Mahatma Gandhi's birthday.",
        },
        {
            "date": "2026-10-03",
            "day": "Saturday",
            "event": "II CA Test Concludes (Odd Semester)",
            "category": "CA Test",
            "semester": "Odd Semester",
            "is_holiday": False,
            "description": "Conclusion of Second Continuous Assessment (II CA) Tests.",
        },
        {
            "date": "2026-10-19",
            "day": "Monday",
            "event": "Ayudha Pooja - Holiday",
            "category": "Holiday",
            "semester": "Odd Semester",
            "is_holiday": True,
            "description": "Festival holiday on account of Ayudha Pooja.",
        },
        {
            "date": "2026-10-20",
            "day": "Tuesday",
            "event": "Vijaya Dasami - Holiday",
            "category": "Holiday",
            "semester": "Odd Semester",
            "is_holiday": True,
            "description": "Festival holiday on account of Vijaya Dasami.",
        },
        {
            "date": "2026-10-23",
            "day": "Friday",
            "event": "Last Working Day for Odd Semester",
            "category": "Semester Date",
            "semester": "Odd Semester",
            "is_holiday": False,
            "description": "Final instructional working day for Odd Semester 2026.",
        },
        {
            "date": "2026-10-30",
            "day": "Friday",
            "event": "Commencement of Comprehensive Examinations (Odd Semester)",
            "category": "Examination",
            "semester": "Odd Semester",
            "is_holiday": False,
            "description": "Comprehensive semester-end theory and practical examinations commence.",
        },
        {
            "date": "2026-11-08",
            "day": "Sunday",
            "event": "Deepavali - Holiday",
            "category": "Holiday",
            "semester": "Odd Semester",
            "is_holiday": True,
            "description": "Festival holiday on account of Deepavali.",
        },

        # --- EVEN SEMESTER 2026-2027 ---
        {
            "date": "2026-12-02",
            "day": "Wednesday",
            "event": "Commencement of Classes for Even Semester",
            "category": "Semester Date",
            "semester": "Even Semester",
            "is_holiday": False,
            "description": "Classes commence for Even Semester (Semester IV for MCA).",
        },
        {
            "date": "2026-12-22",
            "day": "Tuesday",
            "event": "National Mathematics Day (Srinivasa Ramanujan Birthday)",
            "category": "Academic Event",
            "semester": "Even Semester",
            "is_holiday": False,
            "description": "Academic observance celebrating National Mathematics Day in honor of Srinivasa Ramanujan.",
        },
        {
            "date": "2026-12-25",
            "day": "Friday",
            "event": "Christmas - Holiday",
            "category": "Holiday",
            "semester": "Even Semester",
            "is_holiday": True,
            "description": "Public holiday celebrating Christmas.",
        },

        # --- OFFICIAL PSGCAS CALENDAR SPECIFICATION (JANUARY - APRIL) ---
        # January
        {
            "date": "2026-01-01",
            "day": "Thursday",
            "event": "New Year's Day - Holiday",
            "category": "Holiday",
            "semester": "Even Semester",
            "is_holiday": True,
            "description": "Public holiday for New Year's Day.",
        },
        {
            "date": "2026-01-05",
            "day": "Monday",
            "event": "National Birds Day",
            "category": "Academic Event",
            "semester": "Even Semester",
            "is_holiday": False,
            "description": "Observance of National Birds Day.",
        },
        {
            "date": "2026-01-12",
            "day": "Monday",
            "event": "National Youth Day",
            "category": "Academic Event",
            "semester": "Even Semester",
            "is_holiday": False,
            "description": "Observance of National Youth Day (Swami Vivekananda Jayanti).",
        },
        {
            "date": "2026-01-14",
            "day": "Wednesday",
            "event": "Pongal - Holiday",
            "category": "Holiday",
            "semester": "Even Semester",
            "is_holiday": True,
            "description": "State festival holiday for Pongal celebration.",
        },
        {
            "date": "2026-01-15",
            "day": "Thursday",
            "event": "Thiruvalluvar Day - Holiday",
            "category": "Holiday",
            "semester": "Even Semester",
            "is_holiday": True,
            "description": "Public holiday commemorating sage poet Thiruvalluvar.",
        },
        {
            "date": "2026-01-16",
            "day": "Friday",
            "event": "Uzhavar Thirunal - Holiday",
            "category": "Holiday",
            "semester": "Even Semester",
            "is_holiday": True,
            "description": "Public holiday celebrating farmers and harvest (Uzhavar Thirunal).",
        },
        {
            "date": "2026-01-25",
            "day": "Sunday",
            "event": "Founders' Day / National Voters Day",
            "category": "Academic Event",
            "semester": "Even Semester",
            "is_holiday": False,
            "description": "PSG College of Arts & Science Founders' Day & National Voters Day.",
        },
        {
            "date": "2026-01-26",
            "day": "Monday",
            "event": "Republic Day - Holiday",
            "category": "Holiday",
            "semester": "Even Semester",
            "is_holiday": True,
            "description": "National Holiday celebrating Republic Day of India.",
        },
        {
            "date": "2026-01-27",
            "day": "Tuesday",
            "event": "I CA Test (Day 1)",
            "category": "CA Test",
            "semester": "Even Semester",
            "is_holiday": False,
            "description": "First Continuous Assessment (I CA) Test series begins.",
        },
        {
            "date": "2026-01-28",
            "day": "Wednesday",
            "event": "I CA Test (Day 2)",
            "category": "CA Test",
            "semester": "Even Semester",
            "is_holiday": False,
            "description": "First Continuous Assessment (I CA) Test series.",
        },
        {
            "date": "2026-01-29",
            "day": "Thursday",
            "event": "I CA Test (Day 3)",
            "category": "CA Test",
            "semester": "Even Semester",
            "is_holiday": False,
            "description": "First Continuous Assessment (I CA) Test series.",
        },
        {
            "date": "2026-01-30",
            "day": "Friday",
            "event": "I CA Test (Day 4)",
            "category": "CA Test",
            "semester": "Even Semester",
            "is_holiday": False,
            "description": "First Continuous Assessment (I CA) Test series.",
        },
        {
            "date": "2026-01-31",
            "day": "Saturday",
            "event": "I CA Test (Day 5)",
            "category": "CA Test",
            "semester": "Even Semester",
            "is_holiday": False,
            "description": "First Continuous Assessment (I CA) Test series.",
        },

        # February
        {
            "date": "2026-02-01",
            "day": "Sunday",
            "event": "Thaipoosam",
            "category": "Academic Event",
            "semester": "Even Semester",
            "is_holiday": False,
            "description": "Thaipoosam festival day.",
        },
        {
            "date": "2026-02-02",
            "day": "Monday",
            "event": "I CA Test (Day 6 - Final Day)",
            "category": "CA Test",
            "semester": "Even Semester",
            "is_holiday": False,
            "description": "First Continuous Assessment (I CA) Test concluding session.",
        },
        {
            "date": "2026-02-18",
            "day": "Wednesday",
            "event": "Start Date of Examination Fee Payment",
            "category": "Fee Payment",
            "semester": "Even Semester",
            "is_holiday": False,
            "description": "Commencement of Examination fee collection portal for comprehensive exams.",
        },
        {
            "date": "2026-02-21",
            "day": "Saturday",
            "event": "International Mother Language Day",
            "category": "Academic Event",
            "semester": "Even Semester",
            "is_holiday": False,
            "description": "Worldwide observance of International Mother Language Day.",
        },
        {
            "date": "2026-02-28",
            "day": "Saturday",
            "event": "National Science Day",
            "category": "Academic Event",
            "semester": "Even Semester",
            "is_holiday": False,
            "description": "Celebration of Raman Effect discovery on National Science Day.",
        },

        # March
        {
            "date": "2026-03-02",
            "day": "Monday",
            "event": "Last Date for Examination Fee Payment Without Fine",
            "category": "Fee Payment",
            "semester": "Even Semester",
            "is_holiday": False,
            "description": "Deadline to pay even semester comprehensive examination fee without penalty fine.",
        },
        {
            "date": "2026-03-03",
            "day": "Tuesday",
            "event": "World Wildlife Day",
            "category": "Academic Event",
            "semester": "Even Semester",
            "is_holiday": False,
            "description": "Observance of UN World Wildlife Day.",
        },
        {
            "date": "2026-03-08",
            "day": "Sunday",
            "event": "International Women's Day",
            "category": "Academic Event",
            "semester": "Even Semester",
            "is_holiday": False,
            "description": "Celebration of International Women's Day.",
        },
        {
            "date": "2026-03-12",
            "day": "Thursday",
            "event": "Last Date for Examination Fee Payment With Fine",
            "category": "Fee Payment",
            "semester": "Even Semester",
            "is_holiday": False,
            "description": "Final closing date for submission of examination fee with prescribed late fine.",
        },
        {
            "date": "2026-03-15",
            "day": "Sunday",
            "event": "World Consumer Rights Day",
            "category": "Academic Event",
            "semester": "Even Semester",
            "is_holiday": False,
            "description": "Observance of World Consumer Rights Day.",
        },
        {
            "date": "2026-03-20",
            "day": "Friday",
            "event": "Telugu New year Day - Holiday",
            "category": "Holiday",
            "semester": "Even Semester",
            "is_holiday": True,
            "description": "State holiday for Telugu New Year (Ugadi).",
        },
        {
            "date": "2026-03-21",
            "day": "Saturday",
            "event": "Ramzan - Holiday",
            "category": "Holiday",
            "semester": "Even Semester",
            "is_holiday": True,
            "description": "Public holiday celebrating Eid-ul-Fitr (Ramzan).",
        },
        {
            "date": "2026-03-23",
            "day": "Monday",
            "event": "II CA Test (Day 1)",
            "category": "CA Test",
            "semester": "Even Semester",
            "is_holiday": False,
            "description": "Second Continuous Assessment (II CA) Tests commence.",
        },
        {
            "date": "2026-03-24",
            "day": "Tuesday",
            "event": "II CA Test (Day 2)",
            "category": "CA Test",
            "semester": "Even Semester",
            "is_holiday": False,
            "description": "Second Continuous Assessment (II CA) Tests.",
        },
        {
            "date": "2026-03-25",
            "day": "Wednesday",
            "event": "II CA Test (Day 3)",
            "category": "CA Test",
            "semester": "Even Semester",
            "is_holiday": False,
            "description": "Second Continuous Assessment (II CA) Tests.",
        },
        {
            "date": "2026-03-26",
            "day": "Thursday",
            "event": "II CA Test (Day 4)",
            "category": "CA Test",
            "semester": "Even Semester",
            "is_holiday": False,
            "description": "Second Continuous Assessment (II CA) Tests.",
        },
        {
            "date": "2026-03-27",
            "day": "Friday",
            "event": "II CA Test (Day 5)",
            "category": "CA Test",
            "semester": "Even Semester",
            "is_holiday": False,
            "description": "Second Continuous Assessment (II CA) Tests.",
        },
        {
            "date": "2026-03-28",
            "day": "Saturday",
            "event": "II CA Test (Day 6 - Final Day)",
            "category": "CA Test",
            "semester": "Even Semester",
            "is_holiday": False,
            "description": "Conclusion of Second Continuous Assessment (II CA) Tests.",
        },
        {
            "date": "2026-03-31",
            "day": "Tuesday",
            "event": "Mahaveer Jayanthi - Holiday",
            "category": "Holiday",
            "semester": "Even Semester",
            "is_holiday": True,
            "description": "Public holiday celebrating Mahaveer Jayanthi.",
        },

        # April
        {
            "date": "2026-04-03",
            "day": "Friday",
            "event": "Good Friday - Holiday",
            "category": "Holiday",
            "semester": "Even Semester",
            "is_holiday": True,
            "description": "Public holiday on account of Good Friday.",
        },
        {
            "date": "2026-04-14",
            "day": "Tuesday",
            "event": "Dr Ambedkar Jayanthi / Tamil New Year - Holiday",
            "category": "Holiday",
            "semester": "Even Semester",
            "is_holiday": True,
            "description": "Public holiday celebrating Dr. B.R. Ambedkar Jayanthi and Tamil New Year.",
        },
        {
            "date": "2026-04-16",
            "day": "Thursday",
            "event": "Last Working Day for Even Semester",
            "category": "Semester Date",
            "semester": "Even Semester",
            "is_holiday": False,
            "description": "Last instructional working day for Even Semester.",
        },
        {
            "date": "2026-04-20",
            "day": "Monday",
            "event": "Commencement of Comprehensive Examinations",
            "category": "Examination",
            "semester": "Even Semester",
            "is_holiday": False,
            "description": "Commencement of Comprehensive Semester-End Examinations for Even Semester.",
        },
        {
            "date": "2027-04-23",
            "day": "Friday",
            "event": "Comprehensive Examinations Commence (2026-2027 Cycle)",
            "category": "Examination",
            "semester": "Even Semester",
            "is_holiday": False,
            "description": "Comprehensive Examinations commence for the 2026-2027 Even Semester academic cycle.",
        },
    ]

    for cal_item in calendar_data:
        db.add(CalendarEvent(**cal_item))

    db.commit()
    print(f"Successfully seeded: {len(subjects_data)} subjects, {len(timetable_data)} timetable entries, {len(calendar_data)} calendar events.")


if __name__ == "__main__":
    db = SessionLocal()
    try:
        seed_data(db)
    finally:
        db.close()
